version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    restart: always
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ics1802026
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db_scripts:/docker-entrypoint-initdb.d # for DB-centric schema creation

volumes:
  db_data: