FROM postgres:13

ENV POSTGRES_DB=product_db
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=ics1802026

# Expose the default PostgreSQL port
EXPOSE 5432

# The PostgreSQL image automatically handles initialization scripts
# placed in /docker-entrypoint-initdb.d/