import os
from sqlalchemy.schema import CreateTable
from sqlalchemy import create_engine
from sqlalchemy.dialects import postgresql

# Explicitly import Base
from base import Base

# Explicitly import all models to ensure they are registered with Base.metadata
from models.software_apps import software_apps
from models.compatibility_map import compatibility_map
from models.hardware_devices import hardware_devices

def generate_sql():
    # Use a dummy engine, as we only want to compile DDL, not execute
    # The actual connection string doesn't matter here, only the dialect
    engine = create_engine('postgresql://', echo=False) # 'postgresql://' is enough for dialect

    print("-- Generated SQL Schema from SQLAlchemy Models --")
    print("-- Do not edit this file directly. Regenerate if models change. --")
    print("")

    if not Base.metadata.sorted_tables:
        print("Error: No SQLAlchemy models found registered with Base.metadata. "
              "Ensure all model files are correctly imported and inherit from Base.")
        return

    for table in Base.metadata.sorted_tables:
        # Compile CreateTable DDL for PostgreSQL dialect
        compiled_ddl = CreateTable(table).compile(dialect=postgresql.dialect())
        print(str(compiled_ddl) + ";")
        print("")

if __name__ == "__main__":
    # For this script to work, it must be run from the 'backend/db' directory
    # so that 'base' and 'models' can be imported correctly.
    generate_sql()
