-- Generated SQL Schema from SQLAlchemy Models --
-- Do not edit this file directly. Regenerate if models change. --


CREATE TABLE hardware_devices (
	id SERIAL NOT NULL, 
	name VARCHAR NOT NULL, 
	PRIMARY KEY (id)
)

;


CREATE TABLE software_apps (
	id SERIAL NOT NULL, 
	PRIMARY KEY (id)
)

;


CREATE TABLE compatibility_map (
	software_id INTEGER NOT NULL, 
	hardware_id INTEGER NOT NULL, 
	is_compatible BOOLEAN NOT NULL, 
	PRIMARY KEY (software_id, hardware_id), 
	FOREIGN KEY(software_id) REFERENCES software_apps (id), 
	FOREIGN KEY(hardware_id) REFERENCES hardware_devices (id)
)

;

