INSERT INTO hardware (model_name, operate_temperature, input_power, ip_rating, ik_rating, interface, extra_specs) VALUES ('ValueScanIII', '-20°C to 50°C', '5.0 VDC +/- 10%', NULL, NULL, 'USB-HID & USB Virtual COM', '{"approvals": "BSMI, CE & FCC", "dimensions": "102mm (L) x 177mm (W) x 71mm (D)", "drop test": "1.5m", "humidity": "5% to 95% Non-Condensing", "image sensor": "CMOS 1280 x 800", "light source": "RED LED 620nm - 630nm", "processor": "1GHz, X1500", "range": "350mm +/- 50mm", "scan rate": "270 Times per Second", "storage temperature": "-40\u00b0C to 70\u00b0C", "weight": "190g"}');
INSERT INTO hardware (model_name, operate_temperature, input_power, ip_rating, ik_rating, interface, extra_specs) VALUES ('PiP', '0°C to 55°C', '5V USB Powered', NULL, NULL, 'Micro USB (HID & KB)', '{"dimensions": "75.77mm (L) x 70.44mm (W) x 14mm (D)", "humidity": "Max 95% Non-Condensing", "mtbf": "30,000 POH", "storage temperature": "-20\u00b0C to 60\u00b0C", "supported contactless protocols": "Apple VAS & Google Smart Tap 2.1"}');
INSERT INTO hardware (model_name, operate_temperature, input_power, ip_rating, ik_rating, interface, extra_specs) VALUES ('KioskIII', '-25°C to 70°C', 'Input Power: 7.5 - 36VDC
Working Current: <500mA', 'IP 65', 'IK 08', 'RS232, USB', '{"antenna dimensions": "75.1mm (H) 60mm (W) x 17.6mm (D)", "controller dimensions": "105mm (H) x 76.2mm (W) x 22.5mm (D)", "durability": "Weather Proof UV Rated Plastic", "encryption": "AES & TDES", "impact / weather ratings": "IK 08 / IP 65", "key management": "TDES DUKPT", "processor": "ARM Processor", "storage temperature": "-40\u00b0C to 85\u00b0C", "weight": "136g (.30lbs)"}');
INSERT INTO hardware (model_name, operate_temperature, input_power, ip_rating, ik_rating, interface, extra_specs) VALUES ('KioskV', '-30°C to 70°C (Max Change of 10°C per Hour)', '5V via USB', 'IP65', 'IK07', 'BLE (Optional), RS232, TTL & USB', '{"encryption": "AES, RSA, TDES & Transarmor", "key management": "DUKPT", "mtbf": "500,000 Hours", "operating humidity": "Maximum 95% (Non-Condensing)", "storage temperature (sred)": "-30\u00b0C to 85\u00b0C (Non-Condensing)", "storage temperature (non-sred)": "-40\u00b0C to 85\u00b0C (Non-Condensing)", "dimensions": "75 mm (H) x 60 mm (W) x 11.2 mm (D)", "memory": "Flash 16 MB (External Flash Size is 16 MB)", "weight": "1.76 oz"}');
INSERT INTO hardware (model_name, operate_temperature, input_power, ip_rating, ik_rating, interface, extra_specs) VALUES ('SmartPINL80', '-20°C to 70°C', '5VDC; Power Consumption: <200mA', 'IP 65', 'IK 08', 'RS232 & USB', '{"approvals": "CE; FCC; PCI PTS 6.X; REACH; RoHS; VCCI", "dimensions": "45mm (H) x 127mm (W) x 36mm (D)", "display": "128 x 32 Pixels", "esd immunity": "\u00b16kV Contact & \u00b110kV Air Discharge to Exposed Surfaces", "humidity": "15% to 95% Non-Condensing", "impact / weather rating": "IK 08 / IP 65", "keys": "Numeric (10), Operation (2) & Function (3)", "key durability": "Minimum 1,000,000 Key Presses", "key management": "DUKPT", "mtbf": "120,000 Power-On Hours Calculated", "storage temperature": "-40\u00b0C to 80\u00b0C"}');
INSERT INTO hardware (model_name, operate_temperature, input_power, ip_rating, ik_rating, interface, extra_specs) VALUES ('SecureMag', '0°C to 55°C', '+5 VDC +/- 10%, 50mV Ripple Maximum', NULL, NULL, 'USB Keyboard
USB-HID 5.5mA Typical w/ LED
8mA Peak USB Keyboard USB-HID', '{"cable length": "6-Foot Side Exit Cable (Bottom Exit is an Option)", "dimensions": "100mm (L) x 35mm (W) x 30mm (D)", "storage temperature": "-30\u00b0C to 65\u00b0C", "swipe speed": "3 to 60 Inches per Second, Bidirectional", "warranty": "One Year Parts & Labor", "weight": "7 oz."}');
INSERT INTO hardware (model_name, operate_temperature, input_power, ip_rating, ik_rating, interface, extra_specs) VALUES ('MiniMagII', '0°C to 55°C', '+5 VDC from USB Port', NULL, NULL, 'Keyboard (PS/2), RS232, RS232 Port Powered, USB-CDC/HID/KB', '{"cable connector": "Keyboard - 6 Pin Mini - DIN, RS232 DB9F & USB-Type A", "cable length": "6 Foot Side Exit Cable (Bottom Exit Option)", "card speed": "5 to 65 Inches per Second", "dimensions": "90mm (L) x 34mm (W) x 28mm (D)", "humidity": "Maximum 95% Non-Condensing, Dry Storage", "media format": "AAMVA, ISO7811 & Other F2F Formats", "media thickness": "0.015 Inches to 0.05 Inches", "operating life": "1,000,000 Card Swipes Minimum", "slot width": "0.040 Inches", "storage temperature": "-30\u00b0C to 70\u00b0C", "weight": "4.6 oz"}');
INSERT INTO hardware (model_name, operate_temperature, input_power, ip_rating, ik_rating, interface, extra_specs) VALUES ('Shuttle', '0°C to 55°C Non-Condensing', NULL, NULL, NULL, 'Audio Headphone Jack', '{"dimensions": "45mm (H) x 127mm (W) x 36mm (D)", "encryption": "AES & TDES", "humidity": "Maximum 95% Non-Condensing, Dry Storage", "key management": "TDES DUKPT", "media formats": "ISO 7811 & AAMVA", "media thickness": "0.025 Inches to 0.035 Inches", "operating life": "100,000 Card Swipes Minimum", "storage temperature": "-30\u00b0C to 70\u00b0C Non-Condensing", "swipe speed": "5 to 60 Inches per Second, Bidirectional", "warranty": "One Year, Parts & Labor", "weight": "0.832 oz."}');
INSERT INTO hardware (model_name, operate_temperature, input_power, ip_rating, ik_rating, interface, extra_specs) VALUES ('GamingReader', '0°C to 60°C', 'RS232 35m Max. USB +5 DC TTL
Standby Mode: 100μA Max
Operating Mode: 3mA Max', NULL, NULL, 'RS232, TTL, USB', '{"dimensions": "88.66mm (W) x 60mm (D) x 25.4mm (H)", "operating life": "1,000,000 Cycles (Minimum)", "shock": "Sweep 10Hz to 50Hz/min; 294 m/s2 (30G)", "storage temperature": "-40\u00b0C to 60\u00b0C", "swipe speed": "3 to 60 Inches per Second, Bi-Directional", "warranty": "One Year, Parts & Labor", "weight": "136g (.30 lbs)"}');
INSERT INTO hardware (model_name, operate_temperature, input_power, ip_rating, ik_rating, interface, extra_specs) VALUES ('SecureKeyM130', '0°C to 40°C', NULL, NULL, NULL, 'USB-Keyboard & USB-HID', '{"approvals": "FCC Class B & CE, RoHS", "cable connector": "USB-A", "card length / thickness": "Length: 6- Foot / Thickness: 0.015 Inches to 0.038 Inches", "dimensions": "160mm (L) x 95mm (W) x 32mm (D)", "drop test": "24 Inches Height (Drop: 1 Corner, 2-Sidelines, 3-Sides)", "encryption": "AES & TDES", "esd immunity": "4 kV to 8 kV Minimum, After Reset", "humidity": "Maximum 90% Non-Condensing", "key character printing": "Laser", "key management": "TDES DUKPT", "operating life": "MSR: 1,000,000 Swipes", "storage temperature": "-20\u00b0C to 40\u00b0C"}');
INSERT INTO hardware (model_name, operate_temperature, input_power, ip_rating, ik_rating, interface, extra_specs) VALUES ('SecureHead', '-20°C to 70°C', 'Operating Voltage 3V or 5V ± 10%', NULL, NULL, 'SPI, UART, USB-HID, USB-KB', '{"card speed": "3 to 75 Inches per Second", "current": "Active Power Supply Current: 7 mA\nStandby Power Supply Current: 5 mA\nSleep Power Supply Current: USB Sleep 4000 \u03bcA", "dimensions": "48.2mm (L) x 12.20mm (W) x .20mm (H)", "esd": "+4kV Discharge to Head Can", "humidity": "Maximum 95% Non-Condensing", "operating life": "1,000,000 Cycles Minimum", "storage temperature": "-40\u00b0C to 70\u00b0C", "warranty": "One Year, Parts & Labor", "weight": "5.67 Grams"}');
INSERT INTO hardware (model_name, operate_temperature, input_power, ip_rating, ik_rating, interface, extra_specs) VALUES ('2DScan FX200', '-20°C to 60°C', '5VDC +/- 5%', 'IP54', NULL, 'RS-232, USB', '{"symbologies": "-1D: EAN-13, EAN-8, UPC-A, UPE-E, Code 128, Code 39, Codabar, UCC/EAN 128, RSS, ITF, ITF-14, ITF6, Standard 25, Matrix 25, COOP 25, Industrial 25, Plessey, MSI Plessey, Code 11, Code 93, Code 49, Code 16k, etc. -2D: PDF417, QR Code, Data Matrix, Aztec, CSC, Maxicode, Micro QR, Micro PDF 417, GM, Code One, etc.", "image sensor": "CMOS 1280*800", "processor": "1 GHz, X1500", "drop test": "1.5m", "humidity": "5% to 95% (Non-Condensing)", "storage_temperature": "-40\u00b0C to 70\u00b0C", "aiming": "650nm Laser Diode or 518nm Green LED", "dimensions": "41.5mm (W) x 49.5mm (D) x 24.3mm (H)", "scan modes / rate": "Continuous, Level, Pulse & Sense Modes / 60 Frames per Sec.", "weight": "1.98oz (56g)"}');
INSERT INTO hardware (model_name, operate_temperature, input_power, ip_rating, ik_rating, interface, extra_specs) VALUES ('Augusta', '0°C to 55°C', '5V USB Powered', NULL, NULL, 'MSR & EMV: USB-HID, USB-KB', '{"encryption": "AES & TDES", "key management": "TDES DUKPT", "humidity": "Maximum 95% Non-Condensing", "storage temperature": "-25\u00b0C to 65\u00b0C", "dimensions": "45 mm (L) x 127 mm (W) x 36 mm (D)", "reliability": "MSR: 1,000,000 Swipes\nEMV: 500,000 Inserts"}');
INSERT INTO hardware (model_name, operate_temperature, input_power, ip_rating, ik_rating, interface, extra_specs) VALUES ('Omni', '0°C to 55°C', '+5 VDC +/- 10%, 35mA/30mA Maximum', NULL, NULL, 'TTL (TTL Barcode and/or Magnetics Clock & Data), Keyboard Wedge, Standard SIA 26-bit Wiegand, RS232, USB-KB, USB-RS232', '{"cable connector": "TTL - 9 Pin Squeeze, Keyboard - 6 Pin Mini DIN, RS232 - DE9F, TTL Mag / Barcode Combo Readers", "cable length": "6 Foot Straight Cable", "dimensions": "127mm (L) x 52mm (W) x 35mm (D)", "humidity": "Maximum 95% Non-Condensing, Dry Storage", "storage temperature": "-35\u00b0C to 70\u00b0C", "warranty": "One Year, Parts & Labor", "weight": "1.4 lb (Including Power Pack)"}');